# .golangci.toml
[run]
timeout = "5m"
skip-dirs = [".github"]

[linters]
enable = [
  "gofmt",
  "revive",       # Replace golint
  "govet",
  "staticcheck",
  "unused",
  "errcheck",
  "ineffassign",
  "misspell",
]

[linters-settings.gofmt]
simplify = true

[linters-settings.revive]
confidence = 0.8  # Equivalent to golint's min-confidence

[linters-settings.staticcheck]
checks = ["all"]

[linters-settings.misspell]
locale = "US"

[issues]
[[issues.exclude-rules]]
path = "main.go"
linters = ["revive"]  # Update to revive
max-issues-per-linter = 50
max-same-issues = 10