# .golangci.toml
[run]
timeout = "5m"

[linters]
enable = [
  "gofmt",
  "revive",
  "govet",
  "staticcheck",
  "unused",
  "errcheck",
  "ineffassign",
  "misspell",
]

[linters-settings.gofmt]
simplify = true

[linters-settings.revive]
confidence = 0.8

[linters-settings.staticcheck]
checks = ["all"]

[linters-settings.misspell]
locale = "US"

[issues]
[[issues.exclude-rules]]
path = "main.go"
linters = ["revive"]
max-issues-per-linter = 50
max-same-issues = 10
exclude-dirs = [".github"]  # Replaced skip-dirs