# .golangci.toml
[run]
timeout = "3m"
skip-dirs = [".github"]

[linters]
enable = [
  "gofmt",
  "golint",
  "govet",
  "staticcheck",
  "unused",
  "errcheck",
  "ineffassign",
  "misspell",
]

[linters-settings.gofmt]
simplify = true

[linters-settings.golint]
min-confidence = 0.8

[linters-settings.staticcheck]
checks = ["all"]

[linters-settings.misspell]
locale = "US"

[issues]
[[issues.exclude-rules]]
path = "main.go"
linters = ["golint"]
max-issues-per-linter = 50
max-same-issues = 10