name: Build Traefik Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'  # Matches go.mod

      # Install golangci-lint (latest version)
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
          $(go env GOPATH)/bin/golangci-lint --version  # Verify version

      # Run linting
      - name: Lint code
        run: |
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m

      # Build the plugin
      - name: Build plugin
        run: |
          GO111MODULE=on go build -buildmode=plugin -o traefik-plugin-block-useragents.so main.go

      # Upload the .so file as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: traefik-plugin-block-useragents.so
          path: traefik-plugin-block-useragents.so
          retention-days: 7