name: Build Traefik Plugin

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    env:
        GO_VERSION: '1.22.0' # Latest stable Go version
        GOLANGCI_LINT_VERSION: v1.61.0 # Latest golangci-lint

    # Set up the working directory
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
      # Set up Go
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
            go-version: ${{ env.GO_VERSION }}
        id: go

      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
                ${{ runner.os }}-go-

      # Install golangci-lint (latest version)
      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}
          $(go env GOPATH)/bin/golangci-lint --version  # Verify version

      # Check dependencies
      - name: Check and get dependencies
        run: |
            go mod tidy
            go mod download
      
      # Run linting
      - name: Lint code
        run: |
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m
      
      # Run tests
      - name: Run tests
        run: |
          go test ./...

      # Build the plugin
      # - name: Build plugin
      #   run: |
      #     go build -v -buildmode=plugin -o traefik-plugin-block-useragents.so block_useragents.go

      # Upload the .so file as an artifact
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: block_UserAgents.so
      #     path: block_UserAgents.so
      #     retention-days: 7